name: RecipeManager
description: Add, edit or remove recipes and fuels
version: 2.0TEST
author: Digi
website: http://dev.bukkit.org/server-mods/recipemanager/
dev-url: http://dev.bukkit.org/server-mods/recipemanager/
main: digi.recipeManager.RecipeManager
softdepend: [Vault, iConomy]